mysql:
    build: ./mysql
    ports:
        - "3306:3306"
    container_name: mysql
    environment:
        'IP': '192.168.99.100'
        'PORT': '3306'
        'DATABASE': 'sakila'
        'USER': 'root'
        'PASSWORD': '123456'

base:
    build: ./base
    environment:
        'COUNTRY_ID':'10'
        'CUSTOMER_ID':'10'

