version: '3'
services:
  mysql:
      build: ./docker/mysql
      container_name: mysql
      environment:
          IP: 192.168.99.100
          PORT: 3306
          DATABASE: sakila
          USER: root
          PASSWORD: "123456"

  java:
      build: ./docker/java
      container_name: myjava
      environment:
          COUNTRY_ID: 10
          CUSTOMER_ID: 10