version: "3"
services:
  mysql3:
    container_name: mysql3
    build: ./docker/mysql
    image: javatest/mysql:1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      IP: "192.168.99.100"
      PORT: 3306
      DATABASE: sakila
      USER: root
      PASSWORD: "123456"
  java3:
    container_name: java3
    build: ./docker/java
    image: javatest/java:1.0
    depends_on:
      - mysql3
    links:
      - mysql3
    environment:
      COUNTRY_ID: 11
      CUSTOMER_ID: 10
      MYSQL_IP: 192.168.99.100
      MYSQL_PORT: 3306